### ISSUE TITLE
Comment from wildcard blokada

### ISSUE THREAD

**Issue by Thomas499** [Rhodizzle/hosts#1]
Blokada admins deleted my comment https://github.com/blokadaorg/blokada/issues/48#issuecomment-476127136. I will post it here where they can't delete it before you have a chance to read it.

------------------------ the deleted comment below ------------------------

Careful, I was banned from telegram for expressing how bad the UI of V4 was and trying to explain they should ask for feedback on a clickable mock up before they spend weeks programming something that everyone hates. 

I do have wildcard functionality working on v3.8 if you want the compiled apk let me know your telegram username and I will be happy to send it to you. Any feedback on it would be greatly appreciated. So far, it seems the only way to block ads on apps like IMDb TV app (official movie app of amazon). I've noticed you can have around 60 wildcards on low end devices without noticeable slowdown. If you use 200 wildcards on low end devices web browsing is noticeably slower. The 4k amazon firestick is a high end device that can run 200+ wildcards without any noticeable slowdown. I included three list you can choose from that have wildcards.

The blokada admins scrapped the pull request that I made that included wildcard functionality because they made such drastic changes to the way the code works in v4. While I was programming the wildcard functionality they were working on v4 and they were not posting the changes to the code structure to the github account because they wanted everything to be a secrete. This resulted in everything that I programmed trying to help not being easily compatible with v4 because they wanted to be secrete. Not very productive.

**Comment by Rhodizzle** [comment]
Hm, thanks for the heads up and offer. I'm not a fan of taking .apks from strangers though, so I'll pass on that 😂😂

Shame about the developers. Not very pragmatic.

**Comment by rpeter85** [comment]
To get things straight:
1.) you were not banned, you were muted, for a reason
2.) the reason was the tone you used, and that we asked **multiple** times to change. You did not.
3.) you tried to prove your commit, which is based on you own experience, with a very limited scope, is a must have, while you stated you are doing "research"
4.) you stated you have samples to rely on, and you "proposed changes" based on them, but I'm very interested from where do you have the samples, because even we, at Blokada don't have data from users. If the "source" we talk about is the Telegram group, and a few you know in person, I would like to tell you that covers about the 1% of our user base.
5.) your code was failing at multiple level, this is why it was declined.
6.) the code is kept secret till the first public release. It is to ensure the app's stability, tested on a smaller group. This is not a new thing, it goes so since 2.4 or so.
7.) If we wanted to keep everything secret, Blokada shouldn't be open source

Feel free to fork the application and modify the code. It is free and open source.

**Comment by Thomas499** [comment]
1. I can not access the blokada group on telegram even a week later. Pretty sure that is banned. 
2. tone read from typed words? I think its easy for you to misinterpret tone when reading. I apologize for the wording that gave the impression of bad tone. I was only trying to help. 
3. prove my commit? - Like state if you enable fallback and have default dns chosen it doesn't check for if there is an issue it just checks for if the dns is local which will 100% be the case if connected by wifi and default dns is chosen, and if so all it does is switch between cloudfair and the default every 30 seconds or so and makes the app fight. And each time this happens it redownloads the list and goes through the upload process. In short, the phone battery will drain pretty quickly and blokada won't block anything because it will be constantly redownloading list? That's pretty easy to prove. - I'm not sure what you mean by Research. Are you referring to when I tried to explain you should make a clickable mock up that takes maybe 10 minutes per page, and show on telegram what the proposed ui looks like and get feedback from the users on it and possible changes before weeks are spent programming it? My experience tells me this would have saved you a lot of time, and would have resulted in a much better v4 because the current ui on v4 is very very bad because you didn't get user feedback "do research" on the proposed changes first
4. I have no idea what you mean by samples. Are you referring to the non-functional clickable mock ups that just show the users what the proposed UI would be like and their feedback? You stated you had two years worth of research that convienced you the users would like the new UI based on surveys. But you didn't show them the actual UI before you spent weeks programming it. And you lack of interaction with the users (asking them how they felt about a mock up of the layout, which would have taken 10 minutes per page to do) resulted in an absolute mess after weeks were wasted programming something in complete secrete.
5. Would you like to try out the compiled apk? When you changed up the code structure in v4 you made significant changes in how it blocks which my code wasn't expecting. I could not have anticipated these changes. Had you posted the changes to the github page I could have included the differences when I was programming the wildcard functionality. But you didn't post any changes until the v4 was complete which was weeks worth of changes in one post. Every programmer out there that wants to help is going to run into the same issue. Any changes they are making could be at the same time when 20% of the app has already been re-written by developers but hasn't been introduced. 
6. Which is why wildcard functionality that I spent a week learning how to program into foreign code wasn't compatible with the new version. The secretiveness of your methods resulted in v4 which no one finds comprehensible, intuitive, or user friendly in any way. What is the point of the telegram group if not to ask for opinions of new features and new ui's before you spend weeks programming them? I'm just trying to help you learn how to not make the same mistake again. Ask for user input. interact with them.

**Comment by ps100000** [comment]
Github is a platform for the exchange of source code and the simple management of different versions. It is not intended as a platform for such flame wars. So please just stop. :roll_eyes:

**Comment by Thomas499** [comment]
Apparently Peter (Blokada admin) decided to block me on github according to github because of content posted here https://github.com/blokadaorg/blokada/issues/441 which had nothing unacceptable it in it was just recommendations. 
![image](https://user-images.githubusercontent.com/38442058/61803038-4dbfa780-ade6-11e9-805f-2b3d1f8ce665.png)
